### PR TITLE
Add Multistage Build

### PR DESCRIPTION
**Pull request by rdmolony**
Only 10MB smaller than non-multistage build but splits up
download and install steps rather than compressing them into
a single RUN command.  v910 downloads fine but fails during install
so by splitting up these steps problematic installs don't need to
redownload every time

Need to modify the build command to build v930:
```bash
docker build --target runtime -t energyplus-runtime --build-arg ENERGYPLUS_VERSION=9.3.0 --build-arg ENERGYPLUS_TAG=v9.3.0 --build-arg ENERGYPLUS_SHA=baff08990c --build-arg ENERGYPLUS_INSTALL_VERSION=9-3-0 .
```
Also have a v910 branch at rdmolony/energyplus-docker that may be
of interest if you'd like to push a v910 version to dockerhub

### CODE REVIEW

**Comment by rdmolony** [comment]
Weirdly (caught by Travis) the `runtime` image failed to run E+ for v930 due to:
```bash
EnergyPlus: error while loading shared libraries: libX11.so.6: cannot open shared object file: No such file or directory
```
I had a poke around the `base` image and found the missing dependency:
```bash
❯ docker build --target base -t energyplus-base --build-arg ENERGYPLUS_VERSION=9.3.0 --build-arg ENERGYPLUS_TAG=v9.3.0 --build-arg ENERGYPLUS_SHA=baff08990c --build-arg ENERGYPLUS_INSTALL_VERSION=9-3-0 .
❯ docker run --rm -it energyplus-base
root@95a3ec309567:/# find . -name libX11.so.6
./usr/lib/x86_64-linux-gnu/libX11.so.6
```

Then it failed on missing `libexpat.so.1`
```bash
❯ docker run --rm -it energyplus-base
root@e567614841aa:/# find . -name libexpat.so.1
./lib/x86_64-linux-gnu/libexpat.so.1
```

It now runs fine after copying the directories `./usr/lib/x86_64-linux-gnu/` & `./lib/x86_64-linux-gnu/` to an `ubuntu` (and not `debian-slim`) runtime

**Comment by nllong** [comment]
Thanks for this PR! We just updated this project to use GitHub action and the tar.gz files for installing EnergyPlus. Can you resolve the conflicts in the Dockerfile and let us know when this is ready for review again? Thanks for your help here!

**Comment by rdmolony** [comment]
No problem at all 😃

Here's how the runtime image compares in size:

Runtime:
```bash
root@471acc503b31:/# du -h --max-depth=1
4.0K    ./home
4.0K    ./srv
616K    ./etc
4.0K    ./opt
12K     ./root
13M     ./lib
4.0K    ./mnt
55M     ./usr
4.0K    ./media
4.0K    ./lib64
0       ./sys
0       ./dev
3.8M    ./sbin
4.0K    ./boot
4.8M    ./bin
20K     ./run
du: cannot access './proc/13/task/13/fd/3': No such file or directory
du: cannot access './proc/13/task/13/fdinfo/3': No such file or directory
du: cannot access './proc/13/fd/4': No such file or directory
du: cannot access './proc/13/fdinfo/4': No such file or directory
0       ./proc
4.0K    ./tmp
4.7M    ./var
195M    ./EnergyPlus-9.5.0-de239b2e5f-Linux-Ubuntu18.04-x86_64
275M    .
```

Latest NREL/docker-energyplus@develop:
```bash
root@70d014a99970:/# du -h --max-depth=1
4.0K    ./home
4.0K    ./srv
1.3M    ./etc
4.0K    ./opt
12K     ./root
13M     ./lib
4.0K    ./mnt
59M     ./usr
4.0K    ./media
4.0K    ./lib64
0       ./sys
0       ./dev
3.8M    ./sbin
4.0K    ./boot
4.8M    ./bin
20K     ./run
du: cannot access './proc/11/task/11/fd/3': No such file or directory
du: cannot access './proc/11/task/11/fdinfo/3': No such file or directory
du: cannot access './proc/11/fd/4': No such file or directory
du: cannot access './proc/11/fdinfo/4': No such file or directory
0       ./proc
4.0K    ./tmp
6.8M    ./var
195M    ./EnergyPlus-9.5.0-de239b2e5f-Linux-Ubuntu18.04-x86_64
283M    .
```

Weirdly `docker` is currently showing the runtime image as larger:
```bash
❯ docker image ls
REPOSITORY           TAG       IMAGE ID       CREATED          SIZE
energyplus-runtime   latest    a19347898aaa   4 minutes ago    311MB
energyplus-develop   latest    6fdcca67b6f0   11 minutes ago   283MB
energyplus-base      latest    353ad990bc9c   49 minutes ago   978MB
ubuntu               18.04     81bcf752ac3d   3 weeks ago      63.1MB
```
---

I also noticed that ENERGYPLUS_TAG is the same as ENERGYPLUS_VERSION in the Dockerfile, should it be taken out?

---

Let me know what you think!

**Comment by nllong** [comment]
This looks great! 1/3 of the size sounds like some great improvements.

I'm sure that ENERGYPLUS_TAG and ENERGYPLUS_VERSION used to be different in the past, if they are the same, then I think we should remove `ENERGYPLUS_TAG`.

**Comment by rdmolony** [comment]
It's was still a little bigger than the current master Docker image called `energyplus-develop` above at `311MB` vs `283MB`.  What was holding us back was the workaround lines which are 12.3MB and 33.3MB respectively:

```Dockerfile
# Copy shared libraries libX11.so.6 & libexpat.so.1 required to run energyplus
RUN apt-get update && apt-get install libx11-6:armhf
COPY --from=base /usr/lib/x86_64-linux-gnu/libX11.so.6 /usr/lib/x86_64-linux-gnu/libX11.so.6
COPY --from=base /lib/x86_64-linux-gnu/ /lib/x86_64-linux-gnu/
```

```bash
❯ docker history energyplus-runtime
IMAGE          CREATED       CREATED BY                                      SIZE      COMMENT
a19347898aaa   3 hours ago   CMD ["/bin/bash"]                               0B        buildkit.dockerfile.v0
<missing>      3 hours ago   ENV PATH=/EnergyPlus-9.5.0-de239b2e5f-Linux-…   0B        buildkit.dockerfile.v0
<missing>      3 hours ago   COPY /lib/x86_64-linux-gnu/ /lib/x86_64-linu…   12.3MB    buildkit.dockerfile.v0
<missing>      3 hours ago   COPY /usr/lib/x86_64-linux-gnu/ /usr/lib/x86…   33.3MB    buildkit.dockerfile.v0
<missing>      3 hours ago   COPY /var/simdata /var/simdata # buildkit       326kB     buildkit.dockerfile.v0
<missing>      3 hours ago   COPY EnergyPlus-9.5.0-de239b2e5f-Linux-Ubunt…   202MB     buildkit.dockerfile.v0
<missing>      3 hours ago   ENV SIMDATA_DIR=/var/simdata                    0B        buildkit.dockerfile.v0
<missing>      3 hours ago   ENV ENERGYPLUS_DOWNLOAD_BASENAME=EnergyPlus-…   0B        buildkit.dockerfile.v0
<missing>      3 hours ago   ENV ENERGYPLUS_SHA=de239b2e5f                   0B        buildkit.dockerfile.v0
<missing>      3 hours ago   ENV ENERGYPLUS_VERSION=9.5.0                    0B        buildkit.dockerfile.v0
<missing>      3 hours ago   ARG ENERGYPLUS_SHA                              0B        buildkit.dockerfile.v0
<missing>      3 hours ago   ARG ENERGYPLUS_VERSION                          0B        buildkit.dockerfile.v0
<missing>      3 weeks ago   /bin/sh -c #(nop)  CMD ["/bin/bash"]            0B        
<missing>      3 weeks ago   /bin/sh -c mkdir -p /run/systemd && echo 'do…   7B        
<missing>      3 weeks ago   /bin/sh -c [ -z "$(apt-get indextargets)" ]     0B        
<missing>      3 weeks ago   /bin/sh -c set -xe   && echo '#!/bin/sh' > /…   745B      
<missing>      3 weeks ago   /bin/sh -c #(nop) ADD file:e05689b5b0d51a231…   63.1MB    
```

>  `/bin/sh -c #(nop) ADD file:e05689b5b0d51a231…   63.1MB` represents the `ubuntu` image

I ran  

```bash
docker run --rm -it energyplus-runtime
```

then

```bash
find /usr/lib/x86_64-linux-gnu/ -name "libexpat.so.1"
```

then back to the `Dockerfile` to copy the files with

```bash
COPY --from=base /usr/lib/x86_64-linux-gnu/libX11.so.1*  ... /usr/lib/x86_64-linux-gnu
```

and rebuilt

```bash
docker build --target runtime -t energyplus-runtime --build-arg ENERGYPLUS_VERSION=9.5.0 --build-arg ENERGYPLUS_TAG=v9.5.0 --build-arg ENERGYPLUS_SHA=de239b2e5f --build-arg ENERGYPLUS_INSTALL_VERSION=9-5-0 .
```

until all missing dependencies had been copied across individually.  It's a little hacky but cuts down the image from `311MB` to `269MB` so now smaller than the current `energyplus-develop`!  Thoughts?

---

I'll make the changes to remove `ENERGYPLUS_TAG` in a separate PR once this PR is finished as the `README.md` needs to be updated too!

**Comment by nllong** [comment]
I think this is a great update. Losing `~40MB` sounds like a great update. Thanks on fixing the ENERGYPLUS_TAG too. Can you check why CI failed on this one?

**Comment by rdmolony** [comment]
Should be fine now!

**Pull request merged**
